### PR TITLE
Improve guile support

### PR DESCRIPTION
**Pull request by rgherdt**
- Implement following features for Guile:

    - $inspect-fallback for GOOP classes/objects and records
    - $binding-documentation for procedures
    - $condition-msg
    - $condition-trace
    - $frame-locals-and-catch-tags
    - $handle-condition
    - $set-package

- Add documentation to setup swank/guile
- Update version of Swank server to 2.28

### CODE REVIEW

**Comment by rgherdt** [comment]
I added a new commit with an implementation of $condition-links and $condition-locations. Now pressing 'v' over a frame jumps to the source location.
I'm not sure I'm using $condition-links as it was supposed to be, see commit message and comment in code.

**Comment by rgherdt** [comment]
@ecraven I just noticed an issue with `$set-package`. After switching to a new module, tracing does no longer work. It complains about missing definitions regarding r7rs-swank internal stuff, for example the procedure `tracing`. Defining `$set-package` as follows works:

```scheme
(define ($set-package name)
  (let ((mod (resolve-module (get-valid-module-name name) #t #:ensure #f)))
    (when mod
      (set-current-module mod)
      (import (guile-swank))))
  (list name name))
```
But I don't think it's a good idea to arbitrarly import `(guile-swank)` in user's code, so I'm not commiting it. I checked `slime.lisp` and they don't need to extra `require` stuff after switching package. Any ideas what is different?

**Comment by ecraven** [comment]
Thank you very much for this!

**Comment by ecraven** [comment]
Regarding the problem with `$set-package`, CL is completely different, they can access symbols from other packages directly. I'll need to think about whether this can be solved in portable Scheme :-/

**Comment by rgherdt** [comment]
> Regarding the problem with `$set-package`, CL is completely different, they can access symbols from other packages directly. I'll need to think about whether this can be solved in portable Scheme :-/

One solution that comes to mind is to define a macro that expands to internal references in some Schemes. For example Guile's @ macro would be a good candidate. One only needs unhygienic macros in some cases, so that  ((@ chicken swank) tracing) could translate to chicken.swank#tracing for instance. Maybe that's also a possible design for a SRFI.

**Pull request merged**
